-- 1. Create the 'notes' table
create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  date date not null unique, -- '2026-02-01'
  message text,
  image_url text,
  spotify_url text,
  is_opened boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (RLS)
alter table public.notes enable row level security;

-- 3. Create Policies
-- Allow Read Access to everyone (since it's a public jar, basically)
create policy "Enable read access for all users"
on public.notes for select
using (true);

-- Allow Update Access (for 'is_opened') - In a real app, this should be more restricted or server-side.
-- For this demo, we'll allow anon updates to 'is_opened'.
create policy "Enable update for anon"
on public.notes for update
using (true)
with check (true);

-- Allow Admin Insert/Update (If we had auth, we'd check ID. For now, allow all for the Admin Dashboard to work without login complexity if you want, OR just use the Dashboard locally).
create policy "Enable insert for all"
on public.notes for insert
with check (true);

-- 4. Create Storage Bucket for Images
insert into storage.buckets (id, name, public)
values ('jar-images', 'jar-images', true)
on conflict (id) do nothing;

-- 5. Storage Policies
create policy "Give public access to jar-images"
on storage.objects for select
using ( bucket_id = 'jar-images' );

create policy "Allow uploads to jar-images"
on storage.objects for insert
with check ( bucket_id = 'jar-images' );

-- 6. Insert Initial Data (Optional - clear first if needed)
-- delete from public.notes;

insert into public.notes (date, message, image_url)
values
('2026-02-01', 'Love is the bridge between two hearts.', null),
('2026-02-02', 'Every moment with you is a treasure.', null),
('2026-02-03', 'You are my sun, my moon, and all my stars.', null),
('2026-02-04', 'My heart beats only for you.', null),
('2026-02-05', 'Together is my favorite place to be.', null),
('2026-02-06', 'Your smile is the most beautiful thing I''ve ever seen.', null),
('2026-02-07', 'I love you more than words can say.', null),
('2026-02-08', 'You complete me.', null),
('2026-02-09', 'Happy Today! You are loved.', 'https://images.unsplash.com/photo-1518568814500-bf0f8d125f46?w=600&auto=format&fit=crop'), -- Example Polaroid Image
('2026-02-10', 'Wait for it... tomorrow holds a kiss.', null),
('2026-02-11', 'Patience is sweet when waiting for you.', null),
('2026-02-12', 'Almost Valentine''s...', null),
('2026-02-13', 'One more sleep.', null),
('2026-02-14', 'Happy Valentine''s Day! Be mine forever.', 'https://images.unsplash.com/photo-1518199266791-5375a83190b3?w=600&auto=format&fit=crop');
